sudo: false
language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
