project: <%= projectName %>

#########################
## Server Options
#########################
server:
  port: 8000
  # If remoteAccess is set to true, you will be able to access your prototype from any device connected to the same network as well as be able to remotely debug them.
  remoteAccess: true

#########################
## Compass Options
#########################
compass:
  debugInfo: false
  # Your dependencies should all go here. The Armadillo will automatically generate your Bundler Gemfile and Gemfile.lock for you. If you run into dependency issues with Bundler, update your gem versions here.
  dependencies:
    sass: ">=3.2.0"
    compass: '>=0.12.1'
    toolkit: '~>1.3.7'
    sassy-buttons: '~>0.2.0'
    modular-scale: '~>1.0.6'
    compass-normalize: '~>1.4.3'
    css_parser: '~>1.3.4'

#########################
## Export Options
#########################
export:
  path: export
  # If deploying somewhere (like GitHub Pages) where your files will not be located at the root directory, this will be the prefix that gets appended to assets run through image-url, style-url, script-url, and component-url
  assetPrefix: <%= projectSlug %>

#########################
## Versioning
#########################
bump:
  # Commit your files to Git after your bump
  commit: false
  # What files to commit. -a for all files
  files:
    - -a
  # Create a Git tag after your bump
  tag: false
  # Push changes to Git upstream after your bump
  push: false

#########################
## Git Options
#########################
git:
  # If you use grunt build --commit, this will be git commit message used
  defaultCommit: Production build and commit
  deployUpstream: origin<% if (ghDeploy) { %>
  deployBranch: gh-pages<% } %>
